# Generated by Django 3.2.13 on 2022-06-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
        ('job_cms_integration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpluginmodel',
            name='job',
        ),
        migrations.AddField(
            model_name='jobpluginmodel',
            name='job',
            field=models.ManyToManyField(to='job.Job'),
        ),
    ]
