# Generated by Django 3.2.13 on 2022-06-15 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_cms_integration', '0002_auto_20220612_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpluginmodel',
            old_name='job',
            new_name='jobs',
        ),
    ]
