# Generated by Django 3.2.13 on 2022-06-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_cms_integration', '0003_rename_job_jobpluginmodel_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpluginmodel',
            name='title',
            field=models.TextField(default='Highlight'),
        ),
    ]
