# Generated by Django 3.2.13 on 2022-06-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('salary', models.IntegerField()),
                ('level', models.CharField(choices=[('JUNIOR', 'Junior'), ('MIDDLE', 'Middle'), ('SENIOR', 'Senior')], max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('recruiter_name', models.CharField(blank=True, max_length=255, null=True)),
                ('recruiter_contacts', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='jobs/')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('engagement_percent', models.IntegerField(blank=True, null=True)),
                ('contact_period', models.CharField(blank=True, max_length=255, null=True)),
                ('published_state', models.BooleanField()),
            ],
        ),
    ]
