# Generated by Django 3.2.13 on 2022-06-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_rename_contact_period_job_contract_period'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ()},
        ),
        migrations.AlterField(
            model_name='job',
            name='level',
            field=models.CharField(choices=[('0', 'Junior'), ('1', 'Middle'), ('2', 'Senior')], max_length=255),
        ),
    ]
